import type { Product } from "@/types/product";

export const categories = [
  {
    id: "men",
    name: "Men's Shoes",
    image: "/mens-athletic-shoes-collection.png",
  },
  {
    id: "women",
    name: "Women's Shoes",
    image: "/womens-fashion-sneakers-collection.png",
  },
  {
    id: "kids",
    name: "Kids' Shoes",
    image: "/kids-colorful-sneakers-collection.png",
  },
  {
    id: "sports",
    name: "Sports Shoes",
    image: "/athletic-running-shoes-collection.png",
  },
];

export const mockProducts: Product[] = [
  // -------------------- MEN (8) --------------------
  {
    id: "1",
    name: "Air Max Pro",
    brand: "Nike",
    price: 1299,
    originalPrice: 1599,
    images: [
      "https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=1260",
    ],
    category: "sports",
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["White/Blue", "Black/Red", "Gray/Orange"],
    rating: 4.5,
    reviews: 128,
    inStock: true,
    description:
      "Premium athletic sneakers with advanced cushioning technology.",
    variants: [
      { id: "1-1", size: "9", color: "White/Blue", stock: 5 },
      { id: "1-2", size: "10", color: "White/Blue", stock: 3 },
    ],
  },
  {
    id: "2",
    name: "Classic Leather Boot",
    brand: "Timberland",
    price: 1899,
    images: [
      "https://images.pexels.com/photos/267301/pexels-photo-267301.jpeg?auto=compress&cs=tinysrgb&w=1260",
    ],
    category: "men",
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["Brown", "Black", "Tan"],
    rating: 4.8,
    reviews: 89,
    inStock: true,
    description: "Durable leather boots perfect for any weather condition.",
    variants: [
      { id: "2-1", size: "9", color: "Brown", stock: 8 },
      { id: "2-2", size: "10", color: "Brown", stock: 4 },
    ],
  },
  {
    id: "3",
    name: "Running Elite",
    brand: "Adidas",
    price: 1499,
    images: [
      "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=1260",
    ],
    category: "sports",
    sizes: ["6", "7", "8", "9", "10", "11"],
    colors: ["Black/White", "Blue/Silver", "Red/Black"],
    rating: 4.6,
    reviews: 203,
    inStock: true,
    description: "High-performance running shoes with responsive cushioning.",
    variants: [
      { id: "3-1", size: "9", color: "Black/White", stock: 12 },
      { id: "3-2", size: "10", color: "Black/White", stock: 7 },
    ],
  },
  {
    id: "4",
    name: "Casual Canvas",
    brand: "Converse",
    price: 799,
    images: [
      "https://images.pexels.com/photos/267202/pexels-photo-267202.jpeg?auto=compress&cs=tinysrgb&w=1260",
    ],
    category: "men",
    sizes: ["5", "6", "7", "8", "9", "10", "11"],
    colors: ["White", "Black", "Red", "Navy"],
    rating: 4.3,
    reviews: 156,
    inStock: true,
    description: "Timeless canvas sneakers for everyday comfort and style.",
    variants: [
      { id: "4-1", size: "9", color: "White", stock: 15 },
      { id: "4-2", size: "10", color: "White", stock: 10 },
    ],
  },
  {
    id: "5",
    name: "AirCourt Retro",
    brand: "NI-K",
    price: 899,
    images: [
      "https://images.pexels.com/photos/2385477/pexels-photo-2385477.jpeg?auto=compress&cs=tinysrgb&w=1260",
    ],
    category: "men",
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["White", "Black"],
    rating: 4.7,
    reviews: 320,
    inStock: true,
    description:
      "Basketball-inspired silhouette with cushioned midsole and premium leather panels.",
    variants: [{ id: "m5-10-white", size: "10", color: "White", stock: 20 }],
  },
  {
    id: "6",
    name: "Trail Grip Runner",
    brand: "Ascent",
    price: 799,
    images: [
      "https://images.pexels.com/photos/1464625/pexels-photo-1464625.jpeg?auto=compress&cs=tinysrgb&w=1260",
    ],
    category: "men",
    sizes: ["8", "9", "10", "11"],
    colors: ["Green", "Black"],
    rating: 4.4,
    reviews: 110,
    inStock: true,
    description:
      "Rugged trail runner with sticky outsole and protective toe cap.",
    variants: [{ id: "m6-9-green", size: "9", color: "Green", stock: 6 }],
  },
  {
    id: "7",
    name: "Lifestyle Knit Slip-on",
    brand: "Everyday",
    price: 549,
    images: [
      "https://images.pexels.com/photos/2048548/pexels-photo-2048548.jpeg?auto=compress&cs=tinysrgb&w=1260",
    ],
    category: "men",
    sizes: ["8", "9", "10", "11", "12"],
    colors: ["Grey", "Navy"],
    rating: 4.3,
    reviews: 92,
    inStock: true,
    description:
      "Comfortable knitted slip-on with soft lining — ideal for urban everyday wear.",
    variants: [{ id: "m7-10-grey", size: "10", color: "Grey", stock: 9 }],
  },
  {
    id: "8",
    name: "Retro Runner 574",
    brand: "NewBalance",
    price: 749,
    images: [
      "https://images.pexels.com/photos/2529147/pexels-photo-2529147.jpeg?auto=compress&cs=tinysrgb&w=1260",
    ],
    category: "men",
    sizes: ["8", "9", "10", "11", "12"],
    colors: ["Grey", "Navy", "Black"],
    rating: 4.5,
    reviews: 145,
    inStock: true,
    description:
      "Iconic retro running silhouette with plush cushioning and supportive fit.",
    variants: [{ id: "m8-10-grey", size: "10", color: "Grey", stock: 11 }],
  },

  // -------------------- WOMEN (8) --------------------
  {
    id: "9",
    name: "Court Classic White",
    brand: "Adidas Femme",
    price: 699,
    images: [
      "https://images.pexels.com/photos/1027130/pexels-photo-1027130.jpeg?auto=compress&cs=tinysrgb&w=1260",
    ],
    category: "women",
    sizes: ["5", "6", "7", "8", "9", "10"],
    colors: ["White", "Green"],
    rating: 4.6,
    reviews: 203,
    inStock: true,
    description:
      "Minimal white leather sneaker with subtle colour accents and supportive sole.",
    variants: [{ id: "w1-7-white", size: "7", color: "White", stock: 14 }],
  },
  {
    id: "10",
    name: "Slip-On Comfort",
    brand: "Skechers",
    price: 549,
    images: ["/converse-canvas-sneakers-classic-style.png"],
    category: "women",
    sizes: ["5", "6", "7", "8", "9"],
    colors: ["Grey", "Black", "White"],
    rating: 4.5,
    reviews: 186,
    inStock: true,
    description:
      "Easy slip-on walking shoe with memory foam insole for all-day comfort.",
    variants: [{ id: "w2-7-grey", size: "7", color: "Grey", stock: 12 }],
  },
  {
    id: "11",
    name: "Cali Star Platform",
    brand: "PUMA Femme",
    price: 649,
    images: ["/womens-fashion-sneakers-collection.png"],
    category: "women",
    sizes: ["5", "6", "7", "8", "9"],
    colors: ["White", "Black"],
    rating: 4.4,
    reviews: 95,
    inStock: true,
    description:
      "Platform sneaker with soft footbed and sleek upper — elevated everyday style.",
    variants: [{ id: "w3-7-white", size: "7", color: "White", stock: 6 }],
  },
  {
    id: "12",
    name: "327 Retro Runner",
    brand: "NewBalance Femme",
    price: 799,
    images: ["/adidas-running-shoes-black-and-white.png"],
    category: "women",
    sizes: ["5", "6", "7", "8", "9"],
    colors: ["Beige", "Black", "Grey"],
    rating: 4.6,
    reviews: 110,
    inStock: true,
    description:
      "70s-inspired retro trainer modernised with a lightweight midsole.",
    variants: [{ id: "w4-8-beige", size: "8", color: "Beige", stock: 7 }],
  },
  {
    id: "13",
    name: "Ballet Slip Minimalist sports",
    brand: "Everyday Femme",
    price: 449,
    images: [],
    category: "women",
    sizes: ["5", "6", "7", "8"],
    colors: ["Nude", "Black", "Soft Pink"],
    rating: 4.2,
    reviews: 67,
    inStock: true,
    description:
      "Lightweight ballet-style slip with cushioned sole and soft lining.",
    variants: [{ id: "w5-6-nude", size: "6", color: "Nude", stock: 9 }],
  },
  {
    id: "14",
    name: "Athleisure Knit Trainer",
    brand: "Fit & Co",
    price: 759,
    images: [
      "https://images.pexels.com/photos/2529157/pexels-photo-2529157.jpeg?auto=compress&cs=tinysrgb&w=1260",
    ],
    category: "women",
    sizes: ["6", "7", "8", "9", "10"],
    colors: ["Blush", "Grey"],
    rating: 4.7,
    reviews: 240,
    inStock: true,
    description:
      "Breathable knit upper with supportive midsole, perfect for gym-to-street.",
    variants: [{ id: "w6-7-blush", size: "7", color: "Blush", stock: 10 }],
  },
  {
    id: "15",
    name: "Canvas Classic leather",
    brand: "Converse Femme",
    price: 549,
    images: [],
    category: "women",
    sizes: ["5", "6", "7", "8", "9"],
    colors: ["Red", "Black", "White"],
    rating: 4.5,
    reviews: 132,
    inStock: true,
    description:
      "Classic canvas upper with elevated platform sole for a modern twist.",
    variants: [{ id: "w7-8-red", size: "8", color: "Red", stock: 8 }],
  },

  // -------------------- KIDS (8) --------------------
  {
    id: "16",
    name: "Easy Velcro Trainer",
    brand: "TinySteps",
    price: 279,
    images: [],
    category: "kids",
    sizes: ["10C", "11C", "12C", "13C", "1Y", "2Y"],
    colors: ["Blue", "Pink", "Green"],
    rating: 4.4,
    reviews: 67,
    inStock: true,
    description: "Simple velcro fastening and flexible sole for growing feet.",
    variants: [{ id: "k1-10c-blue", size: "10C", color: "Blue", stock: 8 }],
  },
  {
    id: "17",
    name: "Mini Superstar",
    brand: "Adidas Kids",
    price: 399,
    images: [
      "https://images.pexels.com/photos/19090/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260",
    ],
    category: "kids",
    sizes: ["10C", "11C", "12C", "13C"],
    colors: ["White", "Black", "Pink"],
    rating: 4.6,
    reviews: 88,
    inStock: true,
    description:
      "Shell-toe inspired kids sneaker with a柔 flexible sole for play.",
    variants: [{ id: "k2-11c-white", size: "11C", color: "White", stock: 10 }],
  },
  {
    id: "18",
    name: "Kids Runner",
    brand: "StrideKids",
    price: 319,
    images: [],
    category: "kids",
    sizes: ["10C", "11C", "12C", "13C"],
    colors: ["Yellow", "Blue", "Red"],
    rating: 4.5,
    reviews: 75,
    inStock: true,
    description:
      "Durable and colorful runner designed for active kids and everyday play.",
    variants: [{ id: "k3-12c-red", size: "12C", color: "Red", stock: 6 }],
  },
  {
    id: "19",
    name: "Junior High Heels",
    brand: "MiniCourt",
    price: 299,
    images: [],
    category: "kids",
    sizes: ["10C", "11C", "12C", "13C"],
    colors: ["Red", "Navy", "Pink"],
    rating: 4.3,
    reviews: 92,
    inStock: true,
    description:
      "High-top style for extra ankle support with soft padded collar.",
    variants: [{ id: "k4-11c-red", size: "11C", color: "Red", stock: 8 }],
  },
  {
    id: "20",
    name: "Flex Runner Junior",
    brand: "Nike Kids",
    price: 379,
    images: [
      "https://images.pexels.com/photos/1478442/pexels-photo-1478442.jpeg?auto=compress&cs=tinysrgb&w=1260",
    ],
    category: "kids",
    sizes: ["10C", "11C", "12C", "13C"],
    colors: ["Black", "Blue", "Purple"],
    rating: 4.2,
    reviews: 60,
    inStock: true,
    description:
      "Easy slip-on and flexible sole for quick on/off during busy days.",
    variants: [{ id: "k5-12c-blue", size: "12C", color: "Blue", stock: 5 }],
  },
  {
    id: "21",
    name: "Tiny Smash Low boots",
    brand: "Puma Kids",
    price: 279,
    images: [],
    category: "kids",
    sizes: ["10C", "11C", "12C", "13C"],
    colors: ["Black", "White"],
    rating: 4.1,
    reviews: 45,
    inStock: true,
    description:
      "Simple low profile sneaker for kids with durable upper and easy-clean surface.",
    variants: [{ id: "k6-11c-black", size: "11C", color: "Black", stock: 7 }],
  },
  {
    id: "22",
    name: "Kids Classics shoes",
    brand: "NewBalance Kids",
    price: 419,
    images: [],
    category: "kids",
    sizes: ["10C", "11C", "12C", "13C"],
    colors: ["Grey", "Pink", "Navy"],
    rating: 4.5,
    reviews: 55,
    inStock: true,
    description:
      "Miniature version of the classic trainer with soft cushioning for little feet.",
    variants: [{ id: "k7-12c-grey", size: "12C", color: "Grey", stock: 4 }],
  },

  // -------------------- ACCESSORIES (8) --------------------
  {
    id: "23",
    name: "Everyday wear Lofer",
    brand: "CarryAll",
    price: 149,
    images: [],
    category: "accessories",
    sizes: [],
    colors: ["Natural", "Black"],
    rating: 4.4,
    reviews: 78,
    inStock: true,
    description:
      "Durable cotton canvas tote with wide handles and roomy interior.",
    variants: [{ id: "a1-natural", size: "", color: "Natural", stock: 25 }],
  },
  {
    id: "24",
    name: "Gym comfort shorts shoes",
    brand: "TravelPro",
    price: 399,
    images: [],
    category: "accessories",
    sizes: [],
    colors: ["Black", "Navy"],
    rating: 4.6,
    reviews: 150,
    inStock: true,
    description:
      "Gym duffel with padded straps, multiple compartments and water-resistant base.",
    variants: [{ id: "a2-black", size: "", color: "Black", stock: 12 }],
  },
  {
    id: "25",
    name: "Minimal Leather Lofer",
    brand: "FineFold",
    price: 199,
    images: [],
    category: "accessories",
    sizes: [],
    colors: ["Tan", "Black"],
    rating: 4.7,
    reviews: 220,
    inStock: true,
    description: "Slim leather wallet with card slots and minimalist profile.",
    variants: [{ id: "a3-tan", size: "", color: "Tan", stock: 40 }],
  },
  {
    id: "26",
    name: "Performance leather shoe",
    brand: "HydraPro",
    price: 99,
    images: [],
    category: "accessories",
    sizes: [],
    colors: ["Silver", "Matte Black"],
    rating: 4.5,
    reviews: 88,
    inStock: true,
    description:
      "Insulated stainless steel bottle keeps drinks cold for 24 hours and hot for 12.",
    variants: [{ id: "a4-black", size: "", color: "Matte Black", stock: 50 }],
  },
  {
    id: "27",
    name: "Classic leather shoe",
    brand: "CapCo",
    price: 79,
    images: [],
    category: "accessories",
    sizes: ["S", "M", "L"],
    colors: ["Navy", "Black", "Tan"],
    rating: 4.2,
    reviews: 67,
    inStock: true,
    description:
      "Classic six-panel cap with embroidered logo and adjustable strap.",
    variants: [{ id: "a5-navy", size: "M", color: "Navy", stock: 30 }],
  },
  {
    id: "28",
    name: "Everyday running shoe",
    brand: "ComfyFeet",
    price: 59,
    images: [],
    category: "accessories",
    sizes: ["S", "M", "L"],
    colors: ["White", "Grey", "Black"],
    rating: 4.4,
    reviews: 98,
    inStock: true,
    description:
      "Soft cotton sock pack — breathable and reinforced at the heel and toe.",
    variants: [{ id: "a6-mix", size: "M", color: "White", stock: 120 }],
  },
  {
    id: "29",
    name: "Compact sport shoes",
    brand: "ShadeLab",
    price: 249,
    images: [],
    category: "accessories",
    sizes: [],
    colors: ["Black", "Tortoise"],
    rating: 4.6,
    reviews: 145,
    inStock: true,
    description:
      "Stylish compact sunglasses with UV400 protection and foldable frame.",
    variants: [{ id: "a7-black", size: "", color: "Black", stock: 28 }],
  },
  {
    id: "30",
    name: "chargable shoes",
    brand: "NeatKit",
    price: 129,
    images: [],
    category: "accessories",
    sizes: [],
    colors: ["Charcoal", "Olive"],
    rating: 4.3,
    reviews: 50,
    inStock: true,
    description:
      "Compact organizer with elastic loops and zip pockets for cables and chargers.",
    variants: [{ id: "a8-charcoal", size: "", color: "Charcoal", stock: 60 }],
  },
  {
    id: "31",
    name: "Foldable sneaker",
    brand: "StormSafe",
    price: 109,
    images: [],
    category: "accessories",
    sizes: [],
    colors: ["Black", "Blue"],
    rating: 4.1,
    reviews: 38,
    inStock: true,
    description:
      "Compact foldable umbrella with windproof frame and quick-dry fabric.",
    variants: [{ id: "a9-black", size: "", color: "Black", stock: 80 }],
  },
  {
    id: "32",
    name: "Minimal partywear boots",
    brand: "BuckleUp",
    price: 189,
    images: [],
    category: "accessories",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Brown"],
    rating: 4.5,
    reviews: 102,
    inStock: true,
    description:
      "Classic leather belt with slim polished buckle and stitched edges.",
    variants: [{ id: "a10-m", size: "M", color: "Black", stock: 36 }],
  },
  {
    id: "33",
    name: "AeroRun Studio Runner",
    brand: "StrideLab",
    price: 8999,
    originalPrice: 1099,
    images: [
      "https://images.pexels.com/photos/1407354/pexels-photo-1407354.jpeg?auto=compress&cs=tinysrgb&w=1260",
    ],
    category: "men",
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["White", "Black", "Grey"],
    rating: 4.6,
    reviews: 210,
    inStock: true,
    description:
      "Lightweight studio-runner with breathable knit upper and responsive midsole cushioning.",
    variants: [
      { id: "m1-9-white", size: "9", color: "White", stock: 12 },
      { id: "m1-10-black", size: "10", color: "Black", stock: 6 },
    ],
  },
  {
    id: "34",
    name: "Classic Leather Low",
    brand: "Heritage Co.",
    price: 649,
    images: [
      "https://images.pexels.com/photos/267294/pexels-photo-267294.jpeg?auto=compress&cs=tinysrgb&w=1260",
    ],
    category: "men",
    sizes: ["8", "9", "10", "11", "12"],
    colors: ["White", "Black", "Tan"],
    rating: 4.3,
    reviews: 134,
    inStock: true,
    description:
      "Timeless leather sneaker finished with a clean silhouette and cushioned footbed.",
    variants: [
      { id: "m2-9-white", size: "9", color: "White", stock: 8 },
      { id: "m2-11-black", size: "11", color: "Black", stock: 4 },
    ],
  },
  {
    id: "35",
    name: "Urban Skate Low",
    brand: "Vans-style",
    price: 549,
    images: [],
    category: "men",
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["Black/White", "Navy", "Red"],
    rating: 4.5,
    reviews: 198,
    inStock: true,
    description:
      "Durable canvas skate shoe with reinforced toe and grippy vulcanized sole.",
    variants: [{ id: "m3-8-bw", size: "8", color: "Black/White", stock: 10 }],
  },
  {
    id: "36",
    name: "Heritage shoe",
    brand: "Puma Co.",
    price: 499,
    images: [],
    category: "men",
    sizes: ["8", "9", "10", "11"],
    colors: ["Black", "Red", "Blue"],
    rating: 4.2,
    reviews: 85,
    inStock: true,
    description:
      "Classic suede upper with retro look and comfortable low-profile fit.",
    variants: [{ id: "m4-9-black", size: "9", color: "Black", stock: 7 }],
  },
];

export const featuredProducts = mockProducts.slice(0, 4);
