import type { Product } from "@/types/product";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Air Max 270",
    brand: "Nike",
    price: 650,
    originalPrice: 800,
    images: [
      "/nike-air-max-270-white-sneakers.png",
      "/nike-air-max-270-side.png",
      "/nike-air-max-270-back-view.png",
    ],
    category: "men",
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["White", "Black", "Blue"],
    rating: 4.5,
    reviews: 128,
    inStock: true,
    description:
      "The Nike Air Max 270 delivers visible Air Max cushioning at the heel and forefoot for all-day comfort and style.",
    variants: [
      { id: "1-7-white", size: "7", color: "White", stock: 5 },
      { id: "1-8-white", size: "8", color: "White", stock: 3 },
      { id: "1-9-white", size: "9", color: "White", stock: 8 },
      { id: "1-10-white", size: "10", color: "White", stock: 2 },
      { id: "1-7-black", size: "7", color: "Black", stock: 4 },
      { id: "1-8-black", size: "8", color: "Black", stock: 6 },
    ],
  },
  {
    id: "2",
    name: "Chuck Taylor All Star",
    brand: "Converse",
    price: 650,
    images: [
      "/converse-chuck-taylor-all-star-red-sneakers.png",
      "/converse-side-view.png",
    ],
    category: "women",
    sizes: ["6", "7", "8", "9", "10"],
    colors: ["Red", "Black", "White"],
    rating: 4.3,
    reviews: 89,
    inStock: true,
    description:
      "The iconic Converse Chuck Taylor All Star sneaker with timeless style and comfort.",
    variants: [
      { id: "2-6-red", size: "6", color: "Red", stock: 7 },
      { id: "2-7-red", size: "7", color: "Red", stock: 4 },
      { id: "2-8-red", size: "8", color: "Red", stock: 9 },
    ],
  },
  {
    id: "3",
    name: "Ultraboost 22",
    brand: "Adidas",
    price: 1900,
    images: [
      "/adidas-ultraboost-22-running-shoes.png",
      "/adidas-ultraboost-side-profile.png",
    ],
    category: "sports",
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["Black", "White", "Grey"],
    rating: 4.7,
    reviews: 156,
    inStock: true,
    description:
      "Experience incredible energy return with the Adidas Ultraboost 22 running shoes.",
    variants: [
      { id: "3-8-black", size: "8", color: "Black", stock: 5 },
      { id: "3-9-black", size: "9", color: "Black", stock: 3 },
      { id: "3-10-black", size: "10", color: "Black", stock: 7 },
    ],
  },
  {
    id: "4",
    name: "Kids Velcro Sneakers",
    brand: "Nike",
    price: 450,
    images: [
      "/kids-nike-velcro-sneakers-colorful.png",
      "/kids-sneakers-side-view.png",
    ],
    category: "kids",
    sizes: ["10C", "11C", "12C", "13C", "1Y", "2Y"],
    colors: ["Blue", "Pink", "Green"],
    rating: 4.4,
    reviews: 67,
    inStock: true,
    description:
      "Easy-on velcro sneakers perfect for active kids with comfortable cushioning.",
    variants: [
      { id: "4-10c-blue", size: "10C", color: "Blue", stock: 8 },
      { id: "4-11c-blue", size: "11C", color: "Blue", stock: 6 },
      { id: "4-12c-pink", size: "12C", color: "Pink", stock: 4 },
    ],
  },
  {
    id: "5",
    name: "Classic Leather",
    brand: "Reebok",
    price: 750,
    originalPrice: 900,
    images: [
      "/reebok-classic-leather-white-sneakers.png",
      "/reebok-classic-leather-profile.png",
    ],
    category: "men",
    sizes: ["8", "9", "10", "11", "12"],
    colors: ["White", "Black", "Navy"],
    rating: 4.2,
    reviews: 94,
    inStock: false,
    description:
      "Timeless style meets modern comfort in the Reebok Classic Leather sneaker.",
    variants: [
      { id: "5-9-white", size: "9", color: "White", stock: 0 },
      { id: "5-10-white", size: "10", color: "White", stock: 0 },
      { id: "5-11-black", size: "11", color: "Black", stock: 0 },
    ],
  },
  {
    id: "6",
    name: "Stan Smith",
    brand: "Adidas",
    price: 850,
    images: [
      "/adidas-stan-smith-white-green-sneakers.png",
      "/adidas-stan-smith-side.png",
    ],
    category: "women",
    sizes: ["6", "7", "8", "9", "10"],
    colors: ["White/Green", "White/Navy", "All White"],
    rating: 4.6,
    reviews: 203,
    inStock: true,
    description:
      "The legendary Adidas Stan Smith tennis shoe with clean, minimalist design.",
    variants: [
      { id: "6-7-white-green", size: "7", color: "White/Green", stock: 6 },
      { id: "6-8-white-green", size: "8", color: "White/Green", stock: 4 },
      { id: "6-9-white-green", size: "9", color: "White/Green", stock: 8 },
    ],
  },
  {
    id: "7",
    name: "LEVEL White Men's Sneakers",
    brand: "Campus",
    price: 999,
    originalPrice: 1200,
    images: ["/white capmus.png", "/white campus 2.png"],
    category: "men",
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["White"],
    rating: 4.5,
    reviews: 128,
    inStock: true,
    description:
      "The Nike Air Max 270 delivers visible Air Max cushioning at the heel and forefoot for all-day comfort and style.",
    variants: [
      { id: "1-7-white", size: "7", color: "White", stock: 5 },
      { id: "1-8-white", size: "8", color: "White", stock: 3 },
      { id: "1-9-white", size: "9", color: "White", stock: 8 },
      { id: "1-10-white", size: "10", color: "White", stock: 2 },
    ],
  },
  {
    id: "8",
    name: "Nike Pro Max 100",
    brand: "Nike",
    price: 1200,
    originalPrice: 1500,
    images: ["/nike.png", "/nike1.png"],
    category: "men",
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["white"],
    rating: 4.5,
    reviews: 128,
    inStock: true,
    description:
      "The Nike Air Max 270 delivers visible Air Max cushioning at the heel and forefoot for all-day comfort and style.",
    variants: [
      { id: "1-7-white", size: "7", color: "White", stock: 5 },
      { id: "1-8-white", size: "8", color: "White", stock: 3 },
      { id: "1-9-white", size: "9", color: "White", stock: 8 },
      { id: "1-10-white", size: "10", color: "White", stock: 2 },
    ],
  },
  {
    id: "9",
    name: "Adidas EVO SL SHOES",
    brand: "Adidas",
    price: 2200,
    originalPrice: 2500,
    images: ["/adidas.png", "/adidas 1.png"],
    category: "men",
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["grey"],
    rating: 4.5,
    reviews: 128,
    inStock: true,
    description:
      "The Nike Air Max 270 delivers visible Air Max cushioning at the heel and forefoot for all-day comfort and style.",
    variants: [
      { id: "1-7-white", size: "7", color: "grey", stock: 5 },
      { id: "1-8-white", size: "8", color: "grey", stock: 3 },
      { id: "1-9-white", size: "9", color: "grey", stock: 8 },
      { id: "1-10-white", size: "10", color: "grey", stock: 2 },
    ],
  },
  {
    id: "10",
    name: "Sketchers women's Air Max",
    brand: "Sketchers",
    price: 2500,
    originalPrice: 3000,
    images: ["/sketchers.png", "/sketchers1.png"],
    category: "women",
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["blue"],
    rating: 4.5,
    reviews: 128,
    inStock: true,
    description:
      "The Nike Air Max 270 delivers visible Air Max cushioning at the heel and forefoot for all-day comfort and style.",
    variants: [
      { id: "1-7-white", size: "7", color: "blue", stock: 5 },
      { id: "1-8-white", size: "8", color: "blue", stock: 3 },
      { id: "1-9-white", size: "9", color: "blue", stock: 8 },
      { id: "1-10-white", size: "10", color: "blue", stock: 2 },
    ],
  },
];

export const categories = [
  {
    id: "men",
    name: "Men's Shoes",
    image: "/mens-athletic-shoes-collection.png",
  },
  {
    id: "women",
    name: "Women's Shoes",
    image: "/womens-fashion-sneakers-collection.png",
  },
  {
    id: "kids",
    name: "Kids' Shoes",
    image: "/kids-colorful-sneakers-collection.png",
  },
  {
    id: "sports",
    name: "Sports Shoes",
    image: "/athletic-running-shoes-collection.png",
  },
];

export const featuredProducts = mockProducts.slice(0, 4);
